server:
  port: 8888
  servlet:
    context-path: /finger
tech:
  es-host: 192.168.1.191:19201
  news-index: web_news
  pic-index: picture
  file-index: file
  preview-service-host: http://192.168.1.191:8102